# Generated by Django 4.2.25 on 2025-10-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('is_emergency', models.BooleanField(default=False)),
                ('auto_flagged_emergency', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING_ADMIN_ASSIGNMENT', 'Pending Admin Assignment'), ('ASSIGNED_TO_SERVICEMAN', 'Assigned to Serviceman'), ('SERVICEMAN_INSPECTED', 'Serviceman Inspected'), ('AWAITING_CLIENT_APPROVAL', 'Awaiting Client Approval'), ('NEGOTIATING', 'Negotiating'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=32)),
                ('initial_booking_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serviceman_estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin_markup_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_address', models.TextField()),
                ('service_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_completed_at', models.DateTimeField(blank=True, null=True)),
                ('work_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
