# Generated by Django 4.2.25 on 2025-10-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicerequest'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paystack_reference'], name='payments_pa_paystac_25e13d_idx'),
        ),
    ]
