# Generated by Django 4.2.25 on 2025-10-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SERVICE_ASSIGNED', 'Service Assigned'), ('PAYMENT_RECEIVED', 'Payment Received'), ('COST_ESTIMATE_READY', 'Cost Estimate Ready'), ('NEGOTIATION_UPDATE', 'Negotiation Update'), ('JOB_COMPLETED', 'Job Completed'), ('BACKUP_OPPORTUNITY', 'Backup Opportunity')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_to_email', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
